Allow Event-based Input Skim with `das-up-to-nevents.py`
cms-PdmV/RelVal pull request #131
Opened 2024-09-08 12:48 UTC by AdrianoDee

With https://github.com/cms-sw/cmssw/pull/45055 we can run data wfs skimming the input based on a maximum number of events (and relying on the golden data certification json). This PR proposes a way to allow the RelVal machine to use this new feature when the `InputInfo` includes a limit on `events` (and no limit on lumisections or runs).

2024-09-09 08:51 UTC, AdrianoDee commented
Are the checks failures related to the PR? It doesn't seems to me

2024-10-17 20:21 UTC, AdrianoDee commented
Hi Geovanny, I've teste with my local setup (using your instructions) and now everything works as it should.

2024-10-21 15:40 UTC, ggonzr requested changes
This patch works as expected. I created this [RelVal](https://cms-pdmv-dev.web.cern.ch/relval/relvals?prepid=CMSSW_14_1_0_pre7__TEST_EVENT_BASED_INPUT_fullsim_noPU_2022_14TeV-RunJetMET02024B_500k-00002&shown=1023&page=0&limit=50) and the new script is loaded in the [cmsDriver.py](https://cms-pdmv-dev.web.cern.ch/relval/api/relvals/get_cmsdriver/CMSSW_14_1_0_pre7__TEST_EVENT_BASED_INPUT_fullsim_noPU_2022_14TeV-RunJetMET02024B_500k-00002) command as required. I suggest a simple change to avoid potential exceptions

2024-10-21 15:40 UTC, ggonzr commented on core/model/relval_step.py
> +            'events': lambda m: m == '' or int(m) > 0,
```suggestion
            'events': lambda m: m == '' or (m.isnumeric() and int(m) > 0),
```

2024-10-21 15:40 UTC, ggonzr commented on core/model/relval_step.py
> +            'events': lambda m: m == '' or int(m) > 0,
Just to be sure the field is always filled with a numeric value and avoid parsing exceptions

2024-10-21 15:46 UTC, AdrianoDee commented on core/model/relval_step.py
> +            'events': lambda m: m == '' or int(m) > 0,
Sure, committed :)

2024-10-21 16:13 UTC, merged